name: Build Vue
on: [push]
defaults:
  run:
    working-directory: ./client
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    
    steps:
    - uses: actions/checkout@v2
    - name: Build Vue
      run: |
            npm install
            npm run build
            cd dist
            git config --global user.email "tafekih@outlook.fr"
            git config --global user.name "Taoufik Fekih"
            git init
            git add -A
            git commit -m 'deploying client'
            git push -f https://FekihTaoufik:${{ secrets.GITHUB_TOKEN }}@github.com/FekihTaoufik/mevn-assignment.git master:gh-pages
      shell: bash
